export const EMPTY_STATE_QUOTES: string[] = [
  "Start with a heading. Or don't. We won't judge.",
  "This page is technically infinite. No pressure.",
  "The backspace key works too. Just saying.",
  "Markdown: because HTML has too many angle brackets.",
  "You're one # away from greatness.",
  "An empty page walks into a bar. The bartender says, 'No body?'",
  "The cursor blinks. The page waits. A love story.",
  "Your future README starts here.",
  "Plot twist: the real content was the friends we made along the way.",
  "Tip: words go here.",
  "In the beginning, there was nothing. Then someone pressed a key.",
  "This space intentionally left blank. For now.",
  "A journey of a thousand words begins with a single keystroke.",
  "Fun fact: this editor won't judge your grammar. Mostly.",
  "Type something. Anything. The page believes in you.",
  "Roses are red, violets are blue, this page is empty, and waiting for you.",
  "Welcome. The page is your oyster. Or canvas. Or whatever metaphor you prefer.",
  "Psst. The source mode is where the magic happens.",
  "You miss 100% of the headings you don't type.",
  "Today's forecast: a blank page with a chance of brilliance.",
  "Breaking news: local page still empty. More at 11.",
  "This page has been staring at you for 0 seconds.",
  "No content detected. Deploying motivational quote.",
  "Achievement unlocked: opened an empty file.",
  "Error 404: content not found. Just kidding. Start typing.",
  "The pen is mightier than the sword. The keyboard is mightier than both.",
  "Warning: writing may lead to satisfaction.",
  "Blank pages are just documents with commitment issues.",
  "Three backticks walk into a bar. The rest is fenced off.",
  "Some call it empty. We call it full of potential.",
  "Protip: Ctrl+` toggles source mode. You're welcome.",
  "What's the markdown for a blank stare? Asking for a friend.",
  "This page is minimalist by default. Maximalist by choice.",
  "A wise dev once said: 'Just start typing.'",
  "This is your page. There are many like it, but this one is yours.",
  "Every great document started as an empty file.",
  "The only thing standing between you and a great doc is a keystroke.",
  "Loading content... just kidding, that's your job.",
  "Friendly reminder: you can't save what doesn't exist yet.",
  "Bold move opening an empty file. We respect that.",
  "Behind every great project is a README that was once this empty.",
  "Your words here could change the world. Or at least confuse a coworker.",
  "A blank page is like a fresh cup of coffee — full of possibility.",
  "This page is judging you silently. Write something already.",
  "Psst — try ## for a subheading. It's life-changing.",
  "The page patiently waits. It has nowhere else to be.",
  "You opened this file on purpose, right?",
  "Unwritten content: the dark matter of documentation.",
  "Writer's block? Try writing 'Hello World'. Classic for a reason.",
  "This file is as empty as a promise to update the docs.",
  "One does not simply leave a markdown file empty.",
  "Pages written today: 0. But who's counting?",
  "Even Shakespeare started with a blank page. Probably.",
  "Fun fact: you can't have typos if you haven't typed anything.",
  "Idle thought: what if the content was inside us all along?",
  "Markdown tip: # is for headings, not existential crises.",
  "You know what would look great here? Words.",
  "Currently buffering... content needed.",
  "This emptiness is a feature, not a bug.",
  "Write first, edit later. That's what Ctrl+Z is for.",
  "Abandon all blankness, ye who enter here.",
  "Table for one? Try the table template below.",
  "Congratulations! You've found the world's most patient page.",
  "This page is a canvas. Your keyboard is the brush. We'll stop now.",
  "Life is short. Write the docs.",
  "Ah, the sweet sound of nothing. Type to ruin it.",
  "Still empty? This page will wait. It's very polite.",
  "Your keyboard has over 100 keys. Any one of them works here.",
  "To write, or not to write. That's not even a question here.",
  "Step 1: Type. Step 2: There is no step 2.",
  "Empty pages don't write themselves. Yet.",
  "If you stare at the page long enough, it stares back.",
  "This page rates your content 10/10. It hasn't seen any yet, but it's optimistic.",
  "Plot twist: the page was inside you all along.",
  "Your magnum opus starts with a single character.",
  "Knock knock. Who's there? Not your content, apparently.",
  "This document has great potential. Like, literally nothing but potential.",
  "Somewhere, a technical writer just felt a disturbance in the force.",
  "The blank page: nature's way of saying 'your turn'.",
  "README? More like READ-ME-WHEN-I-EXIST.",
  "Hot take: empty files deserve love too.",
  "0 words written. Infinity words to go.",
  "Current word count: aspirational.",
  "This page is powered by good intentions and zero content.",
  "Your future self will thank you for writing this. Probably.",
  "Markdown: turning # into headings since 2004.",
  "If this page were a restaurant, the menu would be blank.",
  "Write like no one is reading. Because no one is. Yet.",
  "Fun fact: the average markdown file is not this empty.",
  "This is either a blank page or modern art. You decide.",
  "Caution: contents may shift during editing.",
  "Draft zero: the bravest draft of all.",
  "All dressed up with no content to show.",
  "The void gazes back. It suggests a heading.",
  "Two roads diverged in an empty file. Both lead to source mode.",
  "This isn't writer's block. It's a creative pause.",
  "Somewhere out there, a heading is waiting to be written.",
  "Keep calm and write markdown.",
  "First rule of empty pages: you do not talk about empty pages.",
  "May the source be with you.",
  "Git commit -m 'added nothing'. We've all been there.",
];
